<?php
/*
Plugin Name: Arbain Hadith Random
Plugin URI: http://www.abuaisyah.com/wp-plugin-source/
Description: This plugin will randomly choose a hadith from Arbain Nawawi.
Version: 1.1.02
Author: Abu Aisyah
Author URI: http://www.abuaisyah.com
License: GPL2 or Later
*/
/*
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

class Arbain extends WP_Widget {

	function Arbain() {
		// Instantiate the parent object
		parent::__construct( false, 'Arbain Random Widget' );
	}

	function widget( $args, $instance ) {
		// Widget output
		extract($args);
		
		echo '<div class="widget-title">';
		echo '<h3>'.$instance['ttl'].'</h3>';
		echo '</div>';
		
		$input = $this->arrayArbain();
		$rand_keys = array_rand($input,1);

		$result = $input[$rand_keys];
		
		echo "<div class='textwidget'>";
		echo "<p>".$result[0]." sumber : ".$result[1]."</p>";
		echo "</div>";
	}
	
	function update( $new_cfg, $old_cfg ) {
		// Save widget options
		$cfg = $old_cfg;
		$cfg['ttl'] = $new_cfg['ttl'];
		return $cfg;
	}

	function form( $cfg ) {
		// Output admin widget options form
		_e("Just use it");
		echo '<table style="width:350px">
				<tr>
					<td width="150"><label for="'.$this->get_field_id('ttl').'">'.Title.'</label></td>
					<td><input type="text" id="'.$this->get_field_id('ttl').'" name="'. $this->get_field_name('ttl').'" value="'. htmlspecialchars($cfg['ttl'],ENT_QUOTES, 'UTF-8').'"/></td>
				</tr>
			</table>'; 
	}

	function arrayArbain(){
		$array = array(
			array('Dari Amirul Mu\'minin, (Abu Hafsh atau Umar bin Khottob rodiyallohu\'anhu) dia berkata: "Aku pernah mendengar Rosululloh shollallohu\'alaihi wassalam bersabda: \'Sesungguhnya seluruh amal itu tergantung kepada niatnya, dan setiap orang akan mendapatkan sesuai niatnya. Oleh karena itu, barangsiapa yang berhijrah karena Alloh dan Rosul-Nya, maka hijrahnya kepada Alloh dan Rosul-Nya. Dan barangsiapa yang berhijrah karena (untuk mendapatkan) dunia atau karena wanita yang ingin dinikahinya maka hijrahnya itu kepada apa yang menjadi tujuannya (niatnya).\'"', '(Diriwayatkan oleh dua imam ahli hadits; Abu Abdillah Muhammad bin Ismail bin Ibrohim bin Mughiroh bin Bardizbah Al-Bukhori dan Abul Husain Muslim bin Al-Hajjaj bin Muslim Al-Qusairy An-Naisabury di dalam kedua kitab mereka yang merupakan kitab paling shahih diantara kitab-kitab hadits)'), 
			array('Dari Umar rodhiyallohu\'anhu juga, beliau berkata: Pada suatu hari ketika kami duduk di dekat Rosululloh shollallohu \'alaihi wasallam, tiba-tiba muncul seorang laki-laki yang berpakaian sangat putih dan rambutnya sangat hitam. Pada dirinya tidak tampak bekas dari perjalanan jauh dan tidak ada seorangpun diantara kami yang mengenalnya. Kemudian ia duduk di hadapan Nabi shollallohu \'alaihi wasallam, lalu mendempetkan kedua lututnya ke lutut Nabi, dan meletakkan kedua tangannya di atas kedua pahanya, kemudian berkata: "Wahai Muhammad, terangkanlah kepadaku tentang Islam." Kemudian Rosululloh shollallohu\'alaihi wasallam menjawab: "Islam yaitu: hendaklah engkau bersaksi tiada sesembahan yang haq disembah kecuali Alloh dan sesungguhnya Muhammad adalah utusan Alloh. Hendaklah engkau mendirikan sholat, membayar zakat, berpuasa pada bulan Romadhon, dan mengerjakan haji ke rumah Alloh jika engkau mampu mengerjakannya." Orang itu berkata: "Engkau benar." Kami menjadi heran, karena dia yang bertanya dan dia pula yang membenarkannya. Orang itu bertanya lagi: "Lalu terangkanlah kepadaku tentang iman". (Rosululloh) menjawab: "Hendaklah engkau beriman kepada Alloh, beriman kepada para malaikat-Nya, kitab-kitab-Nya, para utusan-Nya, hari akhir, dan hendaklah engkau beriman kepada taqdir yang baik dan yang buruk."Orang tadi berkata: "Engkau benar." Lalu orang itu bertanya lagi: "Lalu terangkanlah kepadaku tentang ihsan." (Beliau) menjawab: "Hendaklah engkau beribadah kepada Alloh seolah-olah engkau melihat-Nya. Namun jika engkau tidak dapat (beribadah seolah-olah) melihat-Nya, sesungguhnya Ia melihat engkau." Orang itu berkata lagi: "Beritahukanlah kepadaku tentang hari kiamat." (Beliau) mejawab: "Orang yang ditanya tidak lebih tahu daripada yang bertanya." Orang itu selanjutnya berkata: "Beritahukanlah kepadaku tanda-tandanya." (Beliau) menjawab: "Apabila budak melahirkan tuannya, dan engkau melihat orang-orang Badui yang bertelanjang kaki, yang miskin lagi penggembala domba berlomba-lomba dalam mendirikan bangunan." Kemudian orang itu pergi, sedangkan aku tetap tinggal beberapa saat lamanya. Lalu Nabi shollallohu \'alaihi wasallam bersabda: "Wahai Umar, tahukah engkau siapa orang yang bertanya itu ?". Aku menjawab: "Alloh dan Rosul-Nya yang lebih mengetahui." Lalu beliau bersabda: "Dia itu adalah malaikat Jibril yang datang kepada kalian untuk mengajarkan agama kalian."', '(HR. Muslim). '), 
			array('Dari Abu Abdirrohman Abdulloh bin Umar bin Khoththob rodhiyallohu \'anhuma, dia berkata "Aku pernah mendengar Rosululloh shollallohu \'alaihi wasallam bersabda: \'Islam itu dibangun di atas lima perkara, yaitu: Bersaksi tiada sesembahan yang haq kecuali Alloh dan sesungguhnya Muhammad adalah utusan Alloh, menegakkan sholat, mengeluarkan zakat, mengerjakan haji ke Baitulloh, dan berpuasa pada bulan Romadhon."', '(HR.Bukhori dan Muslim)'), 
			array('Dari Abu Abdirrohman, Abdulloh bin Mas\'ud rodhiyallohu\'anhu, dia berkata: "Rosululloh shollallohu \'alaihi wasallam telah bersabda kepada kami dan beliau adalah orang yang selalu benar dan dibenarkan: \'Sesungguhnya setiap orang diantara kamu dikumpulkan kejadiannya di dalam rahim ibunya selama empat puluh hari dalam bentuk nuthfah(air mani), kemudian menjadi \'alaqoh(segumpal darah) selama waktu itu juga (empat puluh hari), kemudian menjadi mudhghoh(segumpal daging) selama waktu itu juga, lalu diutuslah seorang malaikat kepadanya, lalu malaikat itu meniupkan ruh padanya dan ia diperintahkan menulis empat kalimat: Menulis rizkinya, ajalnya, amalnya, dan nasib celakanya atau keberuntungannya. Maka demi Alloh yang tiada tuhan selain-Nya, sesungguhnya ada diantara kamu yang melakukan amalan penduduk surga dan amalan itu mendekatkannya ke surga sehingga jarak antara dia dan surga kurang satu hasta, namun karena taqdir yang telah ditetapkan atas dirinya, lalu dia melakukan amalan penduduk neraka sehingga dia masuk ke dalamnya. Dan sesungguhnya ada seseorang diantara kamu yang melakukan amalan penduduk neraka dan amal itu mendekatkannya ke neraka sehingga jarak antara dia dan neraka hanya kurang satu hasta, namun karena taqdir yang telah ditetapka atas dirinya, lalu dia melakukan amalan penduduk surga sehingga dia masuk ke dalamnya."', '(HR. Bukhori dan Muslim) '), 
			array('Dari Ibunda kaum mu\'minin, Ummu Abdillah \'Aisyah rodhiyallohu \'anha, dia berkata: "Rosululloh shollallohu \'alaihi wasallam pernah bersabda: "Barang siapa yang mengada-adakan sesuatu (amalan) dalam urusan (agama) kami yang bukan dari kami, maka (amalan) itu tertolak.". Dan dalam riwayat Muslim: "Barangsiapa melakukan suatu amalan yang tidak ada perintahnya dari kami, maka itu tertolak."', '(HR. Bukhori dan Muslim)'), 
			array('An-Nu\'man bin Basyir berkata, "Saya mendengar Rasulullah saw. bersabda, \'Yang halal itu jelas dan yang haram itu jelas, dan di antara keduanya terdapat hal-hal musyabbihat (syubhat / samar, tidak jelas halal-haramnya), yang tidak diketahui oleh kebanyakan manusia. Barangsiapa yang menjaga hal-hal musyabbihat, maka ia telah membersihkan kehormatan dan agamanya. Dan, barangsiapa yang terjerumus dalam syubhat, maka ia seperti penggembala di sekitar tanah larangan, hampir-hampir ia terjerumus ke dalamnya. Ketahuilah bahwa setiap raja mempunyai tanah larangan, dan ketahuilah sesungguhnya tanah larangan Allah adalah hal-hal yang diharamkan-Nya. Ketahuilah bahwa di dalam tubuh ada sekerat daging. Apabila daging itu baik, maka seluruh tubuh itu baik; dan apabila sekerat daging itu rusak, maka seluruh tubuh itu pun rusak. Ketahuilah, dia itu adalah hati.\'"', '(HR. Bukhori)'), 
			array('Dari Abu Ruqoyyah Tamiim bin Aus Ad-Daari rodhiyallohu\'anhu, sesungguhnya Nabi shollallohu \'alaihi wasallam pernah bersabda: "Agama itu adalah nasihat". Kami (sahabat) bertanya: "Untuk siapa?" Beliau bersabda: "Untuk Alloh, kitab-Nya, rosul-Nya, pemimpin-pemimpin umat islam, dan untuk seluruh muslimin."', '(HR.Muslim) '), 
			array('Dari Ibnu Umar rodhiyallohu\'anhuma, sesungguhnya Rosululloh shollallohu \'alaihi wasallam pernah bersabda: "Aku diperintahkan untuk memerangi manusia sampai mereka mau mengucapkan laa ilaaha illalloh (Tiada sesembahan yang haq kecuali Alloh), menegakkan sholat, dan membayar zakat. Apabila mereka telah melakukan semua itu, berarti mereka telah memelihara harta dan jiwanya dariku kecuali ada alasan yang hak menurut Islam (bagiku untuk memerangi mereka) dan kelak perhitungannya terserah kepada Alloh subhanahu wata\'ala."', '(HR. Bukhori dan Muslim) '), 
			array('Dari Abu Hurairoh \'Abdurrohman bin Shakhr rodhiyallohu\'anhu, dia berkata: "Aku pernah mendengar Rosululloh shollallohu\'alaihi wasallam bersabda: " Apa saja yang aku larang bagi kamu hendaklah kamu jauhi, dan apa saja yang aku perintahkan kepadamu maka lakukanlah sesuai kemampuanmu. Sesungguhnya kehancuran umat-umat sebelum kamu adalah karena mereka banyak bertanya dan menyelisihi nabi-nabi mereka (tidak mau taat dan patuh)."', '(HR. Bukhori dan Muslim)'), 
			array('Dari Abu Hurairoh rodhiallohu \'anhu, ia berkata: "Rosululloh sholallahu \'alaihi wa sallam pernah bersabda: "Sesungguhnya Alloh itu baik, tidak mau menerima sesuatu kecuali yang baik. Dan sesungguhnya Alloh telah memerintahkan kepada orang-orang mukmin (seperti) apa yang telah diperintahkan kepada para rosul, Alloh berfirman, "Wahai para Rosul makanlah dari segala sesuatu yang baik dan kerjakanlah amal sholih" (QS Al Mukminun: 51). Dan Dia berfirman: "Wahai orang-orang yang beriman, makanlah dari apa-apa yang baik yang telah Kami berikan kepadamu" (QS Al Baqoroh: 172). Kemudian beliau menceritakan kisah seorang laki-laki yang melakukan perjalanan jauh, rambutnya kusut dan berdebu. Dia menengadahkan kedua tangannya ke langit seraya berdoa: "Wahai Robbku, wahai Robbku", sedangkan makanannya haram, minumannya haram, pakaiannya haram, dan (perutnya) dikenyangkan dengan makanan haram, maka bagaimana mungkin orang seperti ini dikabulkan do\'anya."', '(HR. Muslim)'), 
			array('Dari Abu Muhammad Al Hasan bin Ali bin Abu Tholib, cucu Rosululloh sholallahu \'alaihi wa sallam dan kesayangan beliau rodhiallohu \'anhuma, dia berkata: "Aku telah hafal (sabda) dari Rosululloh sholallahu \'alaihi wa sallam: "Tinggalkanlah sesuatu yang meragukanmu kepada sesuatu yang tidak meragukanmu."', '(HR. Tirmidzi dan Nasa\'i. Tirmidzi berkata: Ini adalah Hadits Hasan Shahih) '), 
			array('Dari Abu Hurairoh rodhiallohu \'anhu, dia berkata: "Rosululloh sholallahu \'alaihi wa sallam pernah bersabda: "Sebagian tanda dari baiknya keislaman seseorang ialah ia meninggalkan sesuatu yang tidak berguna baginya."', '(Hadits hasan, diriwayatkan Tirmidzi dan lainnya)'), 
			array('Dari Abu Hamzah Anas bin Malik rodhiallohu \'anhu pelayan Rosululloh sholallahu \'alaihi wa sallam, dari Nabi sholallahu \'alaihi wa sallam, beliau bersabda: "Tidaklah sempurna keimanan salah seorang di antara kamu sehingga ia mencintai bagi saudaranya (sesama muslim) segala sesuatu yang dia cintai bagi dirinya sendiri." ', '(HR. Bukhori dan Muslim)'), 
			array('Dari Ibnu Mas\'ud rodhiallohu \'anhu, dia berkata: "Rosululloh sholallahu \'alaihi wa sallam bersabda: "Tidak halal ditumpahkan darah seorang muslim kecuali karena salah satu di antara tiga alasan: orang yang telah kawin melakukan zina, orang yang membunuh jiwa (orang muslim) dan orang yang meninggalkan agamanya memisahkan diri dari jamaah."', '(HR. Bukhori dan Muslim)'), 
			array('Dari Abu Hurairoh rodhiallohu \'anhu, sesungguhnya Rosululloh sholallahu \'alaihi wa sallam pernah bersabda: "Barang siapa yang beriman kepada Alloh dan hari akhirat, maka hendaklah ia berkata baik atau diam. Dan barang siapa yang beriman kepada Alloh dan hari akhirat, maka hendaklah ia memuliakan tetangganya. Dan barang siapa yang beriman kepada Alloh dan hari akhirat hendaklah ia memuliakan tamunya."', '(HR. Bukhori dan Muslim)'), 
			array('Dari Abu Hurairah rodhiallohu \'anhu, ada seorang laki-laki berkata kepada Nabi sholallahu \'alaihi wa sallam, "Berilah aku wasiat." Rosululloh sholallahu \'alaihi wa sallam bersabda, "Jangan marah!" Dia bertanya berulang-ulang dan tetap dijawab, "Jangan Marah!"', '(HR Bukhori) '), 
			array('Dari Abu Ya\'la Syaddad bin Aus rodhiallohu \'anhu, Rosululloh sholallahu \'alaihi wa sallam pernah bersabda, "Sesungguhnya Alloh mewajibkan (kalian) berbuat baik terhadap segala sesuatu, maka bila kalian hendak membunuh orang (dalam peperangan ataupun yang lainnya), bunuhlah dengan cara yang baik, dan bila kamu menyembelih (binatang), maka sembelihlah dengan cara yang baik, hendaklah kalian menajamkan pisau dan memperlakukan hewan sembelihan dengan lembut."', '(HR Muslim)'), 
			array('Dari Abu Dzar Jundub bin Junadah dan Abu Abdirrahman Mu\'adz bin Jabal rodhiallohu \'anhu, bahwa Rosululloh sholallahu \'alaihi wa sallam pernah bersabda, "Bertakwalah kamu kepada Alloh di mana pun kamu berada, iringilah kesalahanmu dengan kebaikan niscaya ia dapat menghapuskannya dan pergaulilah semua manusia dengan budi pekerti yang baik."', '(HR Tirmidzi. Ia berkata, "Hadits ini hasan. Dalam naskah lainnya dikatakan, hadits ini hasan shohih)'), 
			array('Dari Abul Abbas Abdulloh bin Abbas rodhiallohu \'anhuma beliau berkata: Suatu hari aku berada di belakang Nabi sholallahu \'alaihi wa sallam Lalu beliau bersabda , "Nak, aku akan ajarkan kepadamu beberapa patah kata: Jagalah Alloh, Niscaya Dia akan senantiasa menjagamu. Bila engkau meminta sesuatu, mintalah kepada Alloh, dan bila engkau meminta pertolongan, mintalah pertolongan kepada Alloh. Ketahuilah, jika semua umat manusia bersatu padu untuk memberikan suatu kebaikan kepadamu, niscaya mereka tidak dapat melakukannya kecuali dengan sesuatu yang telah ditulis oleh Alloh bagimu, dan jika semua umat manusia bersatu padu untuk mencelakakanmu, niscaya mereka tidak dapat mencelakakanmu kecuali dengan sesuatu yang telah ditulis oleh Alloh bagimu. Pena telah diangkat dan catatan-catatan telah mengering." Dalam riwayat selain Tirmidzi dengan redaksi: "Jagalah Alloh, niscaya engkau akan senantiasa mendapati-Nya di hadapanmu. Kenalilah Alloh di waktu lapang niscaya Dia akan mengenalimu saat kesulitan, ketahuilah bahwa apa yang ditetapkan luput darimu tidak akan pernah menimpamu dan apa yang telah ditetapkan menimpamu tidak akan pernah luput darimu. Ketahuilah bahwa kemenangan itu selalu mengiringi kesabaran, jalan keluar selalu mengiringi cobaan dan kemudahan itu selalu mengiringi kesusahan." ', '(HR Tirmidzi Dia berkata , "Hadits ini hasan shohih")'), 
			array('Dari Abu Mas\'ud Uqbah bin Amr Al-Anshari Al-Badri rodhiyallohu \'anhu Dia berkata: Rasulullah shollallohu \'alaihi wa sallam pernah bersabda, "Sesungguhnya sebagian ajaran yang masih dikenal umat manusia dari perkataan para nabi terdahulu adalah: \'Bila kamu tidak malu, berbuatlah sesukamu."', '(HR Bukhari)'), 
			array('Dari Abu Amr - ada yang mengatakan Abu Amrah - Sufyan bin Abdillah Ats-Tsaqafi rodhiallohu \'anhu. Dia berkata, "Wahai Rasulullah, Katakanlah kepadaku suatu perkataan tentang Islam, yang tidak mungkin aku tanyakan kepada siapa pun selain kepadamu." Rasulullah shollallohu \'alaihi wa sallam bersabda, " Katakanlah: "Aku beriman kepada Alloh, lalu istiqomahlah."', '(HR Muslim)'), 
			array('Dari Abu Abdillah Jabir bin Abdullah Al-Anshori rodhiallohu \'anhu. Bahwa seorang laki-laki bertanya kepada Rasulullah sholallahu \'alaihi wa sallam, "Apa pendapatmu bila aku telah sholat lima waktu, berpuasa Ramadhan, aku menghalalkan yang halal, dan mengharamkan yang haram, dan aku tidak menambah amalan selain itu, apakah aku akan masuk surga?" Nabi menjawab, "Ya"', '(HR Muslim)'), 
			array('Dari Abu Malik Al-Harits bin Ashim Al-Asy\'ari radhiyallaahu \'anhu, Dia berkata: Rasulullah sholallahu \'alaihi wa sallam pernah bersabda, "Bersuci adalah separuh dari keimanan, ucapan \'Alhamdulillah\' akan memenuhi timbangan, \'subhanalloh walhamdulillah\' akan memenuhi ruangan langit dan bumi, sholat adalah cahaya, dan sedekah itu merupakan bukti, kesabaran itu merupakan sinar, dan Al Quran itu merupakan hujjah yang akan membela atau menuntutmu. Setiap jiwa manusia melakukan amal untuk menjual dirinya, maka sebagian mereka ada yang membebaskannya (dari siksa Alloh) dan sebagian lain ada yang menjerumuskannya (dalam siksa-Nya)."', '(HR Muslim)'), 
			array('Dari Abu Dzar Al-Ghifari rodhiallohu \'anhu dari Nabi sholallahu \'alaihi wa sallam bersabda meriwayatkan firman Alloh \'azza wa jalla, bahwa Dia berfirman, "Wahai hamba-hambaku, sesungguhnya Aku mengharamkan kezaliman atas diri-Ku dan Aku mengharamkannya pula atas kalian, maka janganlah kalian saling menzalimi. Wahai hamba-hambaKu, kalian semua tersesat, kecuali orang yang Aku beri hidayah, maka mintalah hidayah itu kepada-Ku, niscaya kuberikan hidayah itu kepadamu. Wahai hamba-hambaKu, sesungguhnya kalian lapar, kecuali orang-orang yang aku beri makan, maka mintalah makan kepada-Ku, niscaya Aku berikan makanan itu kepadamu. Wahai hamba-hambaKu, sesungguhnya kalian adalah orang-orang tidak berpakaian, kecuali orang-orang yang telah Kuberi pakaian, maka mintalah pakaian kepada-Ku, niscaya Aku berikan pakaian itu kepadamu. Wahai hamba-hambaKu, sesungguhnya kalian senantiasa berbuat dosa di malam dan siang hari sedangkan Aku akan mengampuni semua dosa, maka mintalah ampun kepada-Ku, niscaya Aku ampuni kalian semua. Wahai hamba-hambaKu, sesungguhnya kalian tidak dapat mendatangkan kemanfaatan bagi-Ku sehingga tidak sedikit pun kalian bermanfaat bagi-Ku. Wahai hamba-hambaKu, sesungguhnya kalian semua tidak akan dapat mendatangkan bahaya bagi-Ku sehingga tidak sedikit pun kalian dapat membahayakan-Ku. Wahai hamba-hambaKu, andaikan kalian semua dari yang awal sampai yang terakhir, baik dari bangsa manusia maupun jin, semuanya bertakwa dengan ketakwaan orang yang paling takwa di antara kalian, hal itu tidak menambah sedikit pun dalam Kerajaan-Ku. Wahai hamba-hambaKu, andaikan kalian semua dari yang awal sampai yang terakhir, baik dari bangsa manusia maupun bangsa jin, berdiri di atas satu dataran lalu meminta apa pun kepada-Ku, lalu aku penuhi semua permintaan mereka, hal itu sedikit pun tidak mengurangi kekayaan yang Aku miliki, hanya seperti berkurangnya air samudra ketika dimasuki sebatang jarum jahit (kemudian diangkat). Wahai hamba-hambaKu, semua itu perbuatan kalian yang Aku hitungkan untuk kalian, kemudian Aku membalasnya kepada kalian. Maka barang siapa mendapatkan kebaikan, hendaklah ia memuji Alloh, dan barang siapa mendapatkan selain itu, hendaklah ia tidak mencela kecuali dirinya sendirinya."', '(HR. Muslim)'), 
			array('Dari Abu Dzar rodhiallohu \'anhu dia berkata: Ada sekelompok sahabat Rasulullah melapor, "Wahai Rasulullah orang-orang kaya telah memborong pahala. Mereka sholat sebagaimana kami sholat, mereka berpuasa sebagaimana kami puasa, namun mereka dapat bersedekah dengan kelebihan hartanya." Beliau bersabda, "Bukankah Alloh telah menjadikan bagi kalian apa-apa yang dapat kalian sedekahkan? Sesungguhnya pada setiap tasbih ada sedekah, pada setiap tahmid ada sedekah dan pada setiap tahlil ada sedekah, menyuruh kebaikan adalah sedekah, melarang kemungkaran adalah sedekah, dan mendatangi istrimu juga sedekah." Mereka bertanya. "Wahai Rasulullah, apakah jika seseorang memenuhi kebutuhan syahwatnya itu pun mendatangkan pahala?" Beliau bersabda, "Apa pendapatmu, bila ia menempatkan pada tempat yang haram, bukankah ia berdosa? Demikian pula bila ia menempatkan pada tempat yang halal, ia akan mendapatkan pahala."', '(HR. Muslim)'), 
			array('Dari Abu Hurairah rodhiallohu \'anhu dia berkata: Rasulullah sholallahu \'alaihi wa sallam bersabda, "Setiap ruas tulang manusia harus disedekahi setiap hari selagi matahari masih terbit. Mendamaikan dua orang (yang berselisih) adalah sedekah, menolong orang hingga ia dapat naik kendaraan atau mengangkatkan barang bawaan ke atas kendaraannya merupakan sedekah, kata-kata yang baik adalah sedekah, setiap langkah kaki yang engkau ayunkan menuju ke masjid adalah sedekah dan menyingkirkan aral (rintangan, ranting, paku, kayu, atau sesuatu yang mengganggu) dari jalan juga merupakan sedekah."', '(HR. Bukhari dan Muslim) '), 
			array('Dari Nawas bin Sam\'an rodhiallohu \'anhu bahwa Nabi sholallahu \'alaihi wa sallam bersabda, "Kebajikan itu adalah budi pekerti yang baik, dan dosa itu adalah segala sesuatu yang menggelisahkan perasaanmu dan yang engkau tidak suka bila dilihat orang lain."', '(HR. Muslim)'), 
			array('Dan dari Wabishah bin Ma\'bad rodhiallohu \'anhu dia berkata: Aku datang kepada Rasulullah sholallahu \'alaihi wa sallam, beliau bersabda, "Apakah engkau datang untuk bertanya tentang kebajikan?" Aku berkata," Ya." Beliau bersabda, "Bertanyalah kepada hatimu. Kebajikan adalah apa yang menjadikan tenang jiwa dan hati, sedangkan dosa adalah apa yang menggelisahkan jiwa dan menimbulkan keraguan dalam hati, meskipun orang-orang terus membenarkanmu."', '(Hadits hasan yang kami riwayatkan dari Musnad Imam Ahmad bin Hambal dan Musnad Imam Ad-Darimi dengan sanad hasan)'), 
			array('Dari Abu Najih \'Irbadh bin Sariyah rodhiallohu \'anhu dia berkata, "Rasulullah sholallahu \'alaihi wa sallam pernah menasihati kami dengan nasihat yang menggetarkan hati dan mencucurkan air mata. Kami bertanya, "Wahai Rasulullah, seperti ini adalah nasihat perpisahan, karena itu berilah kami nasihat". Beliau bersabda, "Aku wasiatkan kepada kalian untuk tetap menjaga ketakwaan kepada Alloh \'azza wa jalla, tunduk taat (kepada pemimpin) meskipun kalian dipimpin oleh seorang budak Habsyi. Karena orang-orang yang hidup sesudahku akan melihat berbagai perselisihan, hendaklah kalian berpegang teguh kepada sunnah Khulafaur Rasyidin yang diberi petunjuk (Alloh). Peganglah kuat-kuat sunnah itu dengan gigi geraham dan jauhilah ajaran-ajaran yang baru (dalam agama) karena semua bid\'ah adalah sesat."', '(HR. Abu Dawud dan Tirmidzi, ia berkata, "Hadits ini hasan shahih")'), 
			array('Dari Mu\'adz bin Jabal rodhiallohu \'anhu berkata: Aku berkata, "Wahai Rasulullah, beritahu aku amal yang akan memasukanku ke dalam surga dan menjauhkanku dari neraka". Beliau bersabda, "Engkau telah bertanya tentang masalah yang besar. Namun itu adalah perkara yang mudah bagi siapa yang dimudahkan oleh Alloh subhanahu wa ta\'ala. Engkau harus menyembah Alloh dan jangan menyekutukan-Nya dengan apapun, mendirikan sholat, mengeluarkan zakat, berpuasa Ramadhan, dan haji ke Baitullah." Kemudian beliau bersabda, "Maukah kamu aku tunjukkan pintu-pintu kebajikan? Puasa adalah perisai, sedekah memadamkan dosa sebagaimana air memadamkan api, dan shalat di tengah malam." Kemudian beliau membaca ayat. "Lambung mereka jauh dari tempat tidurnya…." Hingga firman-Nya, "…sebagai balasan terhadap apa yang telah mereka kerjakan," (As-Sajdah 16-17). Kemudian beliau bersabda kembali, "Maukah kalian kuberitahu pangkal agama, tiangnya dan puncak tertingginya?". Aku menjawab, "Mau, wahai Rasulullah." Rasulullah shalallahu \'alaihi wa sallam bersabda, "Pokok urusan adalah Islam (masuk Islam dengan syahadat,-pent), tiangnya adalah sholat, dan puncak tertingginya adalah jihad." Kemudian beliau melanjutkan, "Maukah kalian kuberitahu tentang kendali bagi semua itu?" Saya menjawab, "Mau, wahai Rasulullah." Beliau lalu memegang lidahnya dan bersabda, "Jagalah ini." Saya berkata, "Wahai Nabi Alloh, apakah kita akan disiksa karena ucapan-ucapan kita?" Beliau menjawab, "Celaka kamu. Bukankah banyak dari kalangan manusia yang tersungkur kedalam api neraka dengan mukanya terlebih dahulu (dalam riwayat lain: dengan lehernya terlebih dahulu) itu gara-gara buah ucapan lisannya?"', '(HR. Tirmidzi ia berkata, "Hadits ini hasan shahih.")'), 
			array('Abu Tsa\'labah Al-khusyani Jurtsum bin Nasyir ra. meriwayatkan dari Rosulullah saw, beliau bersabda, "Sesungguhnya Allah swt telah menetapkan beberapa kewajiban, janganlah engkau menyepelekannya (meremehkannya), telah menentukan sanksi-sanksi hukum, janganlah engkau melanggar, telah pula mengharamkan beberapa hal, maka janganlah engkau jatuh kedalamnya. Dia juga mendiamkan beberapa hal --karena kasih sayangnya kepada kalian bukannya lupa-- maka janganlah engkau mencari-carinya."', '(Hadits Hasan diriwayatkan oleh Ad-daruquthni, dll)'), 
			array('Dari Abul-Abbas Sahl bin Sa\'d As-Sa\'idi rodhiallohu \'anhu dia berkata: Seorang laki-laki datang kepada Nabi sholallahu \'alaihi wa sallam dan berkata, "Wahai Rasulullah, tunjukkan aku suatu amal, jika aku lakukan akau akan dicintai Alloh dan dicintai oleh manusia. "Rasulullah sholallahu \'alaihi wa sallam bersabda, "Zuhudlah terhadap dunia, niscaya dicintai Alloh dan zuhud lah terhadap apa yang dimiliki orang lain, niscaya mereka akan mencintaimu"', '(Hadits hasan diriwayatkan oleh Ibnu Majah dan imam yang lainnya dengan sanad yang shahih)'), 
			array('Dari Sa\'id Sa\'d bin Malik bin Sinan Al-Khudri rodhiallohu \'anhu, bahwa Rosululloh sholallahu \'alaihi wa sallam beliau bersabda, "Dilarang segala yang bahaya dan menimpakan bahaya."', '(Hadits hasan diriwayatkan oleh Ibnu Majah, Daruquthni, dan yang lainnya dengan disanadkan dan diriwayatkan oleh Malik dalam Al-Muwatha\' secara mursal, dari Amr bin Yahya, dari bapaknya, dari Nabi sholallahu \'alaihi wa sallam dengan meniadakan Abu Sa\'id. Hadits ini menguatkan satu dengan yang lainnya) '), 
			array('Dari Ibnu Abbas rodhiallohu \'anhu bahwa Rasulullah sholallahu \'alaihi wa sallam bersabda, "Jika semua orang dibiarkan menuduh semaunya, niscaya akan ada banyak orang yang menuduh harta suatu kaum dan darahnya. Oleh karenanya, haruslah seseorang yang menuduh itu menunjukkan bukti-buktinya dan yang menolak wajib untuk bersumpah."', '(Hadits hasan diriwayatkan oleh Al-Baihaqi dan yang lainnya, sebagiannya terdapat dalam kitab Shahih)'), 
			array('Dari Abu Sa\'id Al-Khudri rodhiallohu \'anhu dia berkata: Aku mendengar Rosululloh sholallahu \'alaihi wa sallam bersabda: "Barang siapa di antara kalian melihat suatu kemungkaran hendaklah ia mengubah dengan tangannya; jika tidak mampu, maka dengan lisannya; jika ia masih tidak mampu, maka dengan hatinya dan itu adalah selemah-lemahnya iman."', '(HR. Muslim) '), 
			array('Dari Abu Hurairah rodhiallohu \'anhu berkata, Rasulullah sholallahu \'alaihi wa sallam bersabda, "Janganlah kalian saling dengki, jangan saling menipu, jangan saling membenci, jangan saling membelakangi, dan jangan kalian membeli suatu barang yang (akan) dibeli orang. Jadilah kamu sekalian hamba-hamba Alloh yang bersaudara. Seorang muslim adalah saudara bagi muslim yang lainnya, tidak layak untuk saling menzhalimi, berbohong kepadanya dan acuh kepadanya. Taqwa itu ada disini (beliau sambil menunjuk dadanya 3 kali). Cukuplah seseorang dikatakan jahat jika ia menghina saudaranya sesama muslim. Haram bagi seorang muslim dari muslim yang lainnya, darahnya, hartanya, dan harga dirinya"', '(HR. Muslim)'), 
			array('Dari Abu Hurairah rodhiallohu \'anhu, Nabi sholallahu \'alaihi wa sallam bersabda, "Barang siapa melepaskan seorang mukmin dari kesusahan hidup di dunia, niscaya Alloh akan melepaskan darinya kesusahan di hari kiamat, barang siapa memudahkan urusan (mukmin) yang sulit niscaya Alloh akan memudahkan urusannya di dunia dan akhirat. Barang siapa menutup aib seorang muslim, maka Alloh akan menutup aibnya di dunia dan akhirat. Alloh akan menolong seorang hamba, selama hamba itu senantiasa menolong saudaranya. Barang siapa menempuh perjalanan untuk mencari ilmu, maka Alloh akan memudahkan jalan baginya menuju surga. Tidaklah suatu kaum berkumpul di salah satu rumah Alloh untuk membaca Kitabulloh dan mempelajarinya bersama-sama, melainkan akan turun kepada mereka ketenteraman, rahmat Alloh akan menyelimuti mereka, dan Alloh memuji mereka di hadapan (para malaikat) yang berada di sisi-Nya. Barang siapa amalnya lambat, maka tidak akan disempurnakan oleh kemuliaan nasabnya."', '(Hadits dengan redaksi seperti ini diriwayatkan oleh Muslim)'), 
			array('Dari Ibnu Abbas rodhiallohu \'anhu dari Rasulullah sholallahu \'alaihi wa sallam, beliau bersabda menyampaikan apa yang diterimanya dari Tuhannya Alloh \'azza wa jalla. Dia berfirman, "Sesungguhnya Alloh mencatat semua amal kebaikan dan keburukan". Kemudian Dia menjelaskan. "Maka barang siapa telah berniat untuk berbuat suatu kebaikan, tetapi tidak melakukannya, maka Alloh mencatatnya sebagai satu amal kebaikan. Jika ia berniat baik lalu ia melakukannya, maka Alloh mencatatnya berupa sepuluh kebaikan sampai tujuh ratus kali lipat, bahkan masih dilipatgandakan lagi. Dan barang siapa berniat amal keburukan namun tidak melakukannya, Alloh akan mencatatnya sebagai amal kebaikan yang utuh, dan bila ia berniat dan melakukannya, maka Alloh mencatatnya sebagai satu amal keburukan."', '(HR. Bukhori dan Muslim dalam kedua kitab Shahih-nya dengan redaksi tersebut)'), 
			array('Dari Abu Hurairah rodhiallahu \'anhu, berkata: Rasulullah sholallahu \'alaihi wa sallam bersabda bahwa Alloh subhanahu wa ta\'ala berfirman, "Barang siapa memusuhi wali-Ku, maka Aku mengumumkan perang terhadapnya. Tidaklah hamba-Ku mendekatkan diri kepada-Ku dengan sesuatu yang lebih Aku cintai dari apa-apa yang Aku wajibkan kepadanya, dan hamba-Ku itu tetap mendekatkan diri kepada-Ku dengan amalan-amalan sunnah hingga Aku mencintainya. Bila Aku mencintainya, Aku akan menjadi pendengaran yang ia gunakan untuk mendengar, menjadi penglihatannya yang ia gunakan untuk melihat, menjadi tangannya yang ia gunakan untuk menggenggam, dan menjadi kakinya yang ia gunakan untuk berjalan. Jika ia meminta pasti Aku beri, jika ia meminta perlindungan, niscaya Aku lindungi."', '(HR. Bukhari)'), 
			array('Dari Ibnu Abbas rodhiallahu \'anhu bahwa Rasulullah sholallahu \'alaihi wa sallam bersabda, "Sesungguhnya Alloh mengampuni beberapa perilaku umatku, yakni (karena) keliru, lupa dan terpaksa."', '(Hadits hasan diriwayatkan oleh Ibnu Majah, Baihaqi, dan lain-lain)'), 
			array('Dari Ibnu Umar rodhiallahu \'anhu berkata: Rasulullah sholallahu \'alaihi wa sallam memegang pundakku dan bersabda, "Jadilah engkau di dunia ini seperti orang asing atau penyeberang jalan." Ibnu Umar rodhiallahu \'anhu berkata, "Jika kamu berada di sore hari, jangan menunggu pagi hari, dan jika engkau di pagi hari janganlah menunggu sore, manfaatkanlah masa sehat. Sebelum datang masa sakitmu dan saat hidupmu sebelum datang kematianmu."', '(HR. Bukhari)'), 
			array('Dari Abu Muhammad Abdullah bin Amr bin Ash rodhiallahu \'anhu dia berkata: Rasulullah bersabda, "Tidak beriman seseorang di antara kalian sehingga hawa nafsunya mengikuti ajaran yang aku bawa."', '(Hadits shahih, kami riwayatkan dalam kitab Al-Hujjah dengan sanad yang shahih)'), 
			array('Dari Anas bin Malik rodhiallahu \'anhu dia berkata: Aku mendengar Rasulullah sholallahu \'alaihi wa sallam bersabda, "Alloh subhanahu wa ta\'ala berfirman, "Wahai anak Adam, sepanjang engkau memohon kepada-Ku dan berharap kepada-Ku akan Aku ampuni apa yang telah kamu lakukan. Aku tidak peduli. Wahai anak Adam, jika dosa-dosamu setinggi awan di langit kemudian engkau meminta ampunan kepada-Ku akan Aku ampuni. Wahai anak Adam, sesungguhnya jika engkau datang membawa kesalahan sebesar dunia, kemudian engkau datang kepada-Ku tanpa menyekutukan Aku dengan sesuatu apapun, pasti Aku akan datang kepadamu dengan ampunan sebesar itu pula."', '(HR. Tirmidzi, ia berkata, "hadits ini hasan shahih.")'), 
		);

		return $array;
	}
}

function arbain_register_widgets() {
	register_widget( 'Arbain' );
}

add_action( 'widgets_init', 'arbain_register_widgets' );

?>
